sudo: required
dist: trusty

language: go

os:
  - linux

git:
  depth: 3

env:

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh
  - sudo apt-get install qt55base qt55quickcontrols qt55svg qt55declarative
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - export CXX="g++-5" CC="gcc-5"

before_script:
  - export COMPILER=g++-5
  - g++ --version
  - ulimit -c unlimited -S       # enable core dumps
  - git clone -o 44b7f9583ffe0ee0 https://github.com/NixOS/patchelf.git
  - cd patchelf
  - ./configure  && make && sudo make install
  - cd ../

script:
  - cd src/
  - go build -o linuxdeploy
  - go test -v
  - cd ../tests/TestLib
  - qmake "CONFIG+=debug" TestLib.pro
  - make
  - cd ../TestApp
  - qmake "CONFIG+=debug" TestApp.pro
  - make
  - cd ../../src
  - ./linuxdeploy -exe ../tests/TestApp/TestApp -appdir TestApp.AppDir -overwrite -libs ../tests/TestLib/ -qmldir ../tests/TestApp/
  - cd TestApp.AppDir
  - chmod +x TestApp
  - ./TestApp

after_failure:
  - cd ../src
  - cat linuxdeploy.log
