sudo: true
dist: trusty

language: go

os:
  - linux

git:
  depth: 3

env:
  - QUICKBUILD=gotests
  - DEPLOY_TESTS=deploytests

before_install:
  - if [ -n "$DEPLOY_TESTS" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo apt-get update -qq; fi

install:
  - if [ -n "$DEPLOY_TESTS" ]; then sudo apt-get -y install gcc-5 g++-5; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo apt-get -y install binutils xpra automake; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo apt-get install -y gdb; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo apt-get -y install qt55base qt55quickcontrols qt55svg qt55declarative; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
  - export CXX="g++-5" CC="gcc-5"

before_script:
  - export COMPILER=g++-5
  - if [ -n "$DEPLOY_TESTS" ]; then g++ --version; fi
  - ulimit -c unlimited -S       # enable core dumps
  - if [ -n "$DEPLOY_TESTS" ]; then cd vendors/patchelf/src; fi
  - if [ -n "$DEPLOY_TESTS" ]; then g++ -DPACKAGE_NAME=\"patchelf\" -DPACKAGE_TARNAME=\"patchelf\" -DPACKAGE_VERSION=\"0.9\" -DPACKAGE_STRING=\"patchelf\ 0.9\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"patchelf\" -DVERSION=\"0.9\" -DPAGESIZE=4096 -I.    -Wall -g -O2 -MT patchelf.o -MD -MP -MF .deps/patchelf.Tpo -c -o patchelf.o patchelf.cc; fi
  - if [ -n "$DEPLOY_TESTS" ]; then g++ -Wall -g -O2  -o patchelf patchelf.o; fi
  - if [ -n "$DEPLOY_TESTS" ]; then sudo cp patchelf /usr/local/bin/; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cd ../../../; fi

script:
  - if [ -n "$DEPLOY_TESTS" ]; then xpra start :42; fi # start the display to have it ready before needed
  - export DISPLAY=:42 # for the Qml app to start
  - cd src/
  - go build -o linuxdeploy
  - if [ -n "$QUICKBUILD" ]; then go test -v; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cd ../tests/TestLib; fi
  - if [ -n "$DEPLOY_TESTS" ]; then qmake "CONFIG+=debug" TestLib.pro; fi
  - if [ -n "$DEPLOY_TESTS" ]; then make; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cd ../TestApp; fi
  - if [ -n "$DEPLOY_TESTS" ]; then qmake "CONFIG+=debug" TestApp.pro; fi
  - if [ -n "$DEPLOY_TESTS" ]; then make; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cd ../../; fi
  - if [ -n "$DEPLOY_TESTS" ]; then tests/deploy_and_run.sh; fi
  - if [ -n "$DEPLOY_TESTS" ]; then tests/deploy_and_run_blacklist.sh; fi

after_success:
  - if [ -n "$DEPLOY_TESTS" ]; then cat src/linuxdeploy.log; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cat src/linuxdeploy_blacklist.log; fi

after_failure:
  - if [ -n "$DEPLOY_TESTS" ]; then cat src/linuxdeploy.log; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cat src/linuxdeploy_blacklist.log; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cd src/TestApp.AppDir1; fi
  - if [ -n "$DEPLOY_TESTS" ]; then for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/TestApp core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi
  - if [ -n "$DEPLOY_TESTS" ]; then cd ../TestApp.AppDir2; fi
  - if [ -n "$DEPLOY_TESTS" ]; then for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/TestApp core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi
