sudo: required
dist: trusty

language: go

os:
  - linux

git:
  depth: 3

env:
  global:
    - DISPLAY=:42

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh
  - sudo apt-get -y install binutils xpra
  - sudo apt-get -y install qt55base qt55quickcontrols qt55svg qt55declarative
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - export CXX="g++-5" CC="gcc-5"

before_script:
  - export COMPILER=g++-5
  - g++ --version
  - ulimit -c unlimited -S       # enable core dumps
  - git clone -o 44b7f9583ffe0ee0 https://github.com/NixOS/patchelf.git
  - cd patchelf
  - bash ./bootstrap.sh
  - ./configure
  - make -j2
  - sudo make install
  - cd ../

script:
  - xpra start :42 # start the display to have it ready before needed
  - export DISPLAY=:42 # for the Qml app to start
  - cd src/
  - go build -o linuxdeploy
  - go test -v
  - cd ../tests/TestLib
  - qmake "CONFIG+=debug" TestLib.pro
  - make
  - cd ../TestApp
  - qmake "CONFIG+=debug" TestApp.pro
  - make
  - cd ../../
  - tests/deploy_and_run.sh

after_failure:
  - cat src/linuxdeploy.log
